### ISSUE TITLE
Fixing pylons_wallet_impl_test

### ISSUE THREAD

**Issue by afti-githobo** [Pylons-tech/pylons#1435]
## Summary of Bug

Right now, in the testapp_redo branch - and in main once that's merged - `pylons_wallet_impl_test.dart` is commented out, barring a stub `main()` for the runner. That's... bad! It means we currently have no test coverage there. This was done because every test in that file is currently failing in the same (nigh-inexplicable) way:

```2022-11-23T23:21:30.4594640Z To run this test again: /opt/hostedtoolcache/flutter/stable-3.3.9-x64/bin/cache/dart-sdk/bin/dart test /home/runner/work/pylons/pylons/dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart -p vm --plain-name 'should get execution based on id from wallet'
2022-11-23T23:21:30.4595419Z 
2022-11-23T23:21:30.4626605Z 00:51 +57 -15: /home/runner/work/pylons/pylons/dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart: should get all current trades that exist on the chain                                         
2022-11-23T23:21:30.4627713Z 00:51 +57 -15: /home/runner/work/pylons/pylons/dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart: should get all current trades that exist on the chain                                         
2022-11-23T23:21:30.4628171Z FormatException: Invalid length, must be multiple of four (at character 6)
2022-11-23T23:21:30.4628451Z Corey
2022-11-23T23:21:30.4628627Z      ^
2022-11-23T23:21:30.4628737Z 
2022-11-23T23:21:30.4629308Z #0      _Base64Decoder.close (dart:convert/base64.dart:639:7)
2022-11-23T23:21:30.4629651Z #1      Base64Decoder.convert (dart:convert/base64.dart:510:13)
2022-11-23T23:21:30.4629977Z #2      Base64Codec.decode (dart:convert/base64.dart:83:47)
2022-11-23T23:21:30.4630391Z #3      new SDKIPCResponse.fromIPCMessage (package:pylons_sdk/src/features/models/sdk_ipc_response.dart:18:40)
2022-11-23T23:21:30.4630875Z #4      PylonsWalletImpl.handleLink (package:pylons_sdk/src/pylons_wallet/pylons_wallet_impl.dart:80:39)
2022-11-23T23:21:30.4631361Z #5      new PylonsWalletImpl.<anonymous closure> (package:pylons_sdk/src/pylons_wallet/pylons_wallet_impl.dart:50:7)
2022-11-23T23:21:30.4631908Z #6      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
2022-11-23T23:21:30.4632430Z #7      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
2022-11-23T23:21:30.4632923Z #8      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
2022-11-23T23:21:30.4633341Z #9      _rootRunUnary (dart:async/zone.dart:1399:47)
2022-11-23T23:21:30.4633648Z #10     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
2022-11-23T23:21:30.4634295Z #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
2022-11-23T23:21:30.4634675Z #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
2022-11-23T23:21:30.4635053Z #13     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
2022-11-23T23:21:30.4635407Z #14     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
2022-11-23T23:21:30.4635780Z #15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
2022-11-23T23:21:30.4636208Z #16     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
2022-11-23T23:21:30.4636708Z #17     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
2022-11-23T23:21:30.4637112Z #18     _rootRun (dart:async/zone.dart:1383:47)
2022-11-23T23:21:30.4637386Z #19     _CustomZone.run (dart:async/zone.dart:1293:19)
2022-11-23T23:21:30.4637703Z #20     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
2022-11-23T23:21:30.4638091Z #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241:23)
2022-11-23T23:21:30.4638523Z #22     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
2022-11-23T23:21:30.4639033Z #23     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
2022-11-23T23:21:30.4639438Z #24     _rootRun (dart:async/zone.dart:1391:13)
2022-11-23T23:21:30.4639726Z #25     _CustomZone.run (dart:async/zone.dart:1293:19)
2022-11-23T23:21:30.4640025Z #26     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
2022-11-23T23:21:30.4640407Z #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241:23)
2022-11-23T23:21:30.4640791Z #28     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
2022-11-23T23:21:30.4641129Z #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
2022-11-23T23:21:30.4641329Z 
2022-11-23T23:21:30.4641436Z Something went wrong in parsing
2022-11-23T23:21:31.4704753Z 
2022-11-23T23:21:31.4705679Z 00:52 +57 -16: /home/runner/work/pylons/pylons/dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart: should get all current trades that exist on the chain  [E]                                    
2022-11-23T23:21:31.4706576Z   Null check operator used on a null value
2022-11-23T23:21:31.4707847Z   test/pylons_wallet/pylons_wallet_impl_test.dart 134:45  getTradesTest.<fn>.<fn>
2022-11-23T23:21:31.4708178Z   ===== asynchronous gap ===========================
2022-11-23T23:21:31.4708470Z   dart:async                                              new Future.delayed
2022-11-23T23:21:31.4708810Z   test/pylons_wallet/pylons_wallet_impl_test.dart 124:12  getTradesTest.<fn>
2022-11-23T23:21:31.4709061Z 
```

Since this behavior is specific to the tests, and not any production codepaths, a decision was made to kick the can in the interests of shipping, but this is still way too crucial a part of the system to leave it completely untested. So, we need to figure out why that's happening and what to do about it.

## Version

6612e15aca94cbb4d3a40b82856a30f9c286afa8

## Steps to Reproduce

1) uncomment the tests!
2) run them

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
@afti-githobo this got auto-closed, but it's not fixed, right?
